### ISSUE TITLE
Contributing cl-gles-user-module to AGL

### ISSUE THREAD

**Issue by martingkelly** [CogentEmbedded/meta-opencl#1]
Hi,

I really like the cl-gles-user-module recipe! I don't see an explicit license to it, but would you be okay with me contributing it to the Automotive Grade Linux project? I think it will need some build adaptations, but I've already done most of the work to make that happen.

Thanks,
Martin

**Comment by vbce** [comment]
The cl-gles-user-module has the same "closes" license as the original gles-user-module recipe from Renesas. Please, contact Renesas for any legal questions.

Thanks,
Val.

**Comment by martingkelly** [comment]
Thanks. To be clear, I was asking only about the bitbake packaging rather than cl-gles-user-module itself, which I know is proprietary. I see you added an MIT license to the recipes here, so I will use them, with attribution. Thanks!
